#!/usr/bin/env bash
# configure-agent-models — interactive model picker for Company Architect agent tiers
# Usage: ./scripts/configure-agent-models.sh
# Output: writes .opencode/opencode.json (model overrides only, prompts come from ~/.config)

set -euo pipefail
PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CONFIG="$PROJECT_ROOT/.opencode/opencode.json"

# ── Available models (edit this list to add/remove) ──────────────────────────
# Format: "provider/model_id|Display Name"
MODELS=(
  "9router/kg/tencent/hy3:free|HY3 Free (fast, general)"
  "9router/cmc/deepseek/deepseek-v4-pro|DeepSeek V4 Pro (code-heavy)"
  "9router/cmc/xiaomi/mimo-v2.5-pro|MiMo V2.5 Pro (reasoning)"
  "9router/oc/hy3-free|HY3 OC Free"
  "9router/oc/deepseek-v4-flash-free|DeepSeek V4 Flash Free (cheap)"
  "9router/openrouter/deepseek/deepseek-v4-flash:free|DeepSeek Flash via OpenRouter"
  "9router/mistral/devstral-2512|Devstral 2512 (coding)"
  "9router/kg/poolside/laguna-m.1:free|Laguna M.1 Free (code)"
  "9router/kg/stepfun/step-3.7-flash:free|StepFun 3.7 Flash"
  "9router/aa/agnes-2.0-flash|Agnes 2.0 Flash"
  "headroom/claude-haiku-4-5-20251001|Claude Haiku 4.5 (fast, cheap)"
  "headroom/claude-sonnet-4-6|Claude Sonnet 4.6 (balanced)"
  "headroom/claude-opus-4-6|Claude Opus 4.6 (powerful, expensive)"
)

# ── Agent tiers ──────────────────────────────────────────────────────────────
TIERS=(
  "architect|company,swarm|Orchestrator / primary agents"
  "write|company-writer,company-designer,company-strategist|Planning & design agents"
  "work|company-worker,company-team-leader|Execution agents (cheap/fast)"
  "review|company-reviewer,company-auditor,company-benchmarker,company-analyst|Quality audit agents (powerful)"
  "council|company-betriebsrat,swarm-betriebsrat|Works Council agents"
  "integrate|company-integrator,company-activator|Integration & activation"
)

# ── Display ──────────────────────────────────────────────────────────────────
clear
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  Company Architect — Agent Model Configurator              ║"
echo "║  Pick one model per agent tier. Saves to .opencode/opencode.json  ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

show_models() {
  echo "Available models:"
  for i in "${!MODELS[@]}"; do
    IFS='|' read -r id label <<< "${MODELS[$i]}"
    printf "  %2d) %-55s %s\n" "$((i+1))" "$id" "($label)"
  done
  echo ""
}

pick_model() {
  local tier_label="$1"
  local tier_key="$2"
  show_models
  while true; do
    read -r -p "Model for ${tier_label} [1-${#MODELS[@]}, default=1]: " choice
    choice="${choice:-1}"
    if [[ "$choice" =~ ^[0-9]+$ ]] && [ "$choice" -ge 1 ] && [ "$choice" -le "${#MODELS[@]}" ]; then
      IFS='|' read -r model_id _ <<< "${MODELS[$((choice-1))]}"
      echo "$model_id"
      return
    fi
    echo "  Invalid. Enter 1-${#MODELS[@]}."
  done
}

# ── Collect choices ──────────────────────────────────────────────────────────
declare -A TIER_MODELS
declare -A TIER_AGENTS

echo "=== Step 1: Choose default (fallback) model ==="
DEFAULT_MODEL=$(pick_model "DEFAULT (all agents)" "")

for tier in "${TIERS[@]}"; do
  IFS='|' read -r tier_key tier_agents tier_label <<< "$tier"
  echo ""
  echo "=== Step 2.${tier_key}: ${tier_label} ==="
  echo "  Agents in this tier: ${tier_agents}"
  echo "  Use default model? [Y/n/enter model number]"
  read -r -p "  " use_default
  if [[ "$use_default" =~ ^[Yy]?$ ]] || [ -z "$use_default" ]; then
    TIER_MODELS[$tier_key]="$DEFAULT_MODEL"
    echo "  → Using default: $DEFAULT_MODEL"
  elif [[ "$use_default" =~ ^[0-9]+$ ]] && [ "$use_default" -ge 1 ] && [ "$use_default" -le "${#MODELS[@]}" ]; then
    IFS='|' read -r mid _ <<< "${MODELS[$((use_default-1))]}"
    TIER_MODELS[$tier_key]="$mid"
    echo "  → Using: $mid"
  else
    TIER_MODELS[$tier_key]="$DEFAULT_MODEL"
    echo "  → Using default: $DEFAULT_MODEL"
  fi
  TIER_AGENTS[$tier_key]="$tier_agents"
done

# ── Write config ─────────────────────────────────────────────────────────────
echo ""
echo "Writing to $CONFIG ..."

# Build JSON
JSON='{
  "$schema": "https://opencode.ai/config.json",
  "comment": "Auto-generated by scripts/configure-agent-models.sh. Edit models here.",
  "model": "'"$DEFAULT_MODEL"'",
  "agent": {'

first=true
for tier_key in "${!TIER_AGENTS[@]}"; do
  IFS=',' read -ra agents <<< "${TIER_AGENTS[$tier_key]}"
  for agent in "${agents[@]}"; do
    [ "$first" = true ] && first=false || JSON+=","
    JSON+=$'\n    ''"'"$agent"'": { "model": "'"${TIER_MODELS[$tier_key]}"'" }'
  done
done

JSON+=$'\n  }\n}\n'

echo "$JSON" > "$CONFIG"

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  Configuration saved!                                       ║"
echo "║  File: .opencode/opencode.json                      ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "Tier assignments:"
for tier_key in "${!TIER_AGENTS[@]}"; do
  printf "  %-12s → %s\n" "$tier_key" "${TIER_MODELS[$tier_key]}"
done
echo ""
echo "Edit directly: vim $CONFIG"
echo "Re-run: ./scripts/configure-agent-models.sh"
